name: Build PlotSquared (1.21)
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Debug Structure
        run: |
          echo "=== ESTRUTURA DO PROJETO ==="
          ls -la
          echo "=== BUILD.GRADLE ==="
          find . -name build.gradle -exec ls -la {} \;
          echo "=== SUBMÓDULOS ==="
          git submodule status

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build with Gradle (Debug Mode)
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon --stacktrace --scan

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: PlotSquared-JAR
          path: PlotSquared-Bukkit/build/libs/*.jar
