name: Build PlotSquared (Fixed Path)
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Debug Structure
        run: |
          echo "=== ESTRUTURA COMPLETA ==="
          ls -laR
          echo "=== ARQUIVOS GRADLE ==="
          find . -name build.gradle -exec ls -la {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon --stacktrace
          echo "=== ARQUIVOS GERADOS ==="
          find . -name "*.jar" -exec ls -la {} \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlotSquared-JAR
          path: |
            **/PlotSquared-Bukkit/build/libs/*.jar
            **/build/libs/*.jar
          if-no-files-found: error
