name: Build PlotSquared (Gradle)
on:
  workflow_dispatch: # Execução manual
  push:             # Executa ao fazer push
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Debug Structure
        run: |
          echo "=== ESTRUTURA DO REPOSITÓRIO ==="
          ls -la
          echo "=== ARQUIVOS GRADLE ==="
          find . -name build.gradle -exec ls -la {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew :PlotSquared-Bukkit:build -x test --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlotSquared-JAR
          path: PlotSquared-Bukkit/build/libs/*.jar
          if-no-files-found: error
